<a href="https://colab.research.google.com/github/TombCrawler/nihonAI/blob/main/Nov1stMiniGen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nov１st 教授emailより：簡単で構いませんので、メロディデータに対して、
数個の音符列を入力すると、その次の音符を予測する
というモデルをTensorFlowで作る

In [2]:
!pip install midi2audio
!apt install fluidsynth
!pip install pretty_midi
!pip install mido


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fluid-soundfont-gm libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom9 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-render-util0 libxcb-util1 libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1
  libxkbcommon-x11-0 qsynth qt5-gtk-platformtheme qttranslations5-l10n timgm6mb-soundfont
Suggested packages:
  fluid-soundfont-gs qt5-image-formats-plugins qtwayland5 jackd
The following NEW packages will be installed:
  fluid-soundfont-gm fluidsynth libevdev2 libfluidsynth3 libgudev-1.0-0 libinput-bin libinput10
  libinstpatch-1.0-2 libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5
  libqt5svg5 libqt5widgets5 libwacom-bin libwacom-common libwacom9 libxcb-icc

In [ ]:
!pip list | grep jax

In [3]:
!pip install -U jax jaxlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 MB 8.5 MB/s eta 0:00:00
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.4.16+cuda11.cudnn86
    Uninstalling jaxlib-0.4.16+cuda11.cudnn86:
      Successfully uninstalled jaxlib-0.4.16+cuda11.cudnn86
  Attempting uninstall: jax
    Found existing installation: jax 0.4.16
    Uninstalling jax-0.4.16:
      Successfully uninstalled jax-0.4.16


In [4]:
import random
import os
import glob

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.axes3d import Axes3D

import pretty_midi
import IPython.display as ipd
from midi2audio import FluidSynth
from music21 import *

import tensorflow as tf
from sklearn.model_selection import train_test_split
import tensorflow_probability as tfp

import mido
from mido import MidiFile, MidiTrack, Message

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Load the MIDI file
input_midi_path = '/content/drive/MyDrive/chorales/combined_notes2.mid'
output_midi_path = '/content/drive/MyDrive/chorales/generated_note.mid'

In [6]:
class UnsupportedMidiFileException(Exception):
  "Unsupported MIDI File"

In [7]:
# nn_from: the lowest pitch(including this number)
# nn_thru: the heighest pitch (Excluding this number)
# seqlen: the element towards time axis, turn out to be the number of measure. If you give 64 to seqlen based on eighth note, it has 8 measures
#       The song's length(pianoroll.shape[1] must be longer than 64)
# tempo: tempo
def get_pianoroll(midi, nn_from, nn_thru, seqlen, tempo):
  pianoroll = midi.get_piano_roll(fs=2*tempo/60)
  print(f"seqlen!!{seqlen}")
  print(f"piano_roll.shape[1] a.k.a song length!{pianoroll.shape[1]}")
  if pianoroll.shape[1] < seqlen:
    raise UnsupportedMidiFileException
  pianoroll = pianoroll[nn_from:nn_thru, 0:seqlen]
  pianoroll = np.heaviside(pianoroll, 0)
  return np.transpose(pianoroll)

In [18]:
# add rest nodes to the binary piano roll matrix to make the one-hot representation function

# add rest nodes
def add_rest_nodes(pianoroll):
  # make a "rest node series"
  # If all the elemets are zero, the rest node says 1, else 0
  print(f"pinoroll!\n{pianoroll}")
  rests = 1 - np.sum(pianoroll, axis=1)
  print(f"rests!\n{rests}")

  # Make the "rest node series" a 2D array. To use it as a matrix, it's reshaped into a 2D array with a single column.
  rests = np.expand_dims(rests, 1)
  print(f"2D rests!\n{rests}")
  print(f"concatenated!\n{np.concatenate([pianoroll, rests], axis=1)}")
  # Concatenate the binary pianoroll matrix and the rest node series matrix and return it
  return np.concatenate([pianoroll, rests], axis=1)

In [20]:
def read_midi(filename, sop_alto, seqlen):
  # read midi file
  midi = pretty_midi.PrettyMIDI(filename)

  # An Exception error is thrown if there is a modulation(key change)
  if len(midi.key_signature_changes) !=1:
    raise UnsupportedMidiFileException

  # Modulate the given key to C major or C minor
  key_number = midi.key_signature_changes[0].key_number
  # transpose_to_c(midi, key_number)

  # Get Major key(keynode=0) or Minor key(keynode=1)
  # key_number has values ​​from 0 to 11 for major keys and for minor keys,
  # 12~23 is included, so by dividing it by 12 and converting it to an integer,
  # it will be 0 if it is a major key,
  # If it is a minor key, we find the value 1 and assign it to keymode.
  keymode = np.array([int(key_number / 12)])

  # The Exception error thrown when tempo changes
  tempo_time, tempo = midi.get_tempo_changes()
  print(f"tempo_changes{midi.get_tempo_changes()}")
  print(f"tempo_time{tempo_time}, tempo{tempo}")
  if len(tempo) != 1: # counting the number of elements in the tempo array
    raise UnsupportedMidiFileException

  if sop_alto: # The argument is coming in as boolean, True or False
    # The exception thrown if there are less than 2 parts
    if len(midi.instruments) < 2:
      raise UnsupportedMidiFileException

    # Get pianoRoll binary Matrix for each of Soprano and alto parts
    pr_s = get_pianoroll(midi.instruments[0], 36, 84, seqlen, tempo[0])
    pr_a = get_pianoroll(midi.instruments[1], 36, 84, seqlen, tempo[0])
    pr_b = get_pianoroll(midi.instruments[2], 36, 84, seqlen, tempo[0])

    # return pr_s, pr_a, keymode
    return pr_s, pr_a, pr_b, keymode

  else:
    # Get a pianoroll which gathered all the parts
    pr = get_pianoroll(midi, 36, 84, seqlen, tempo[0])
    return pr, keymode

In [15]:
# oA_ Load and preprocess the MIDI data
def load_midi(file_path):
  midi_data = pretty_midi.PrettyMIDI(file_path)
  return midi_data

In [11]:
# oA_ ATTENTION! You may want to modify this function if you want to generate only one single note
def create_sequence_from_midi(idi_data):
  notes = []
  for instrument in midi_data.instruments:
    for note in instrument.notes:
      notes.append((note.pitch, note.start))

  # Sort the notes by start time
  notes.sort(key=lambda x: x[1])

  # Create a list of time intervals between notes
  intervals = [notes[i+1][1] - notes[i][1] for i in range(len(notes)-1)]

  return intervals

In [87]:
# oA_ Load the MIDI data and create a sequence of note intervals
midi_data = load_midi(input_midi_path)
note_intervals = create_sequence_from_midi(midi_data)

In [21]:
# code 4.3, prepare MIDI data for the model
# set the path for the MIDI file
dir = "drive/MyDrive/chorales/midi/"

x_all = [] # the list which stores inputs of soprano melodies
y_all = [] # the list which stores outputs of alto melodies
keymodes = [] # the list which stores the key whether it is major or minor
files = [] # stores the filenames of the MIDI files

# repeat the process with all the midi files
for f in glob.glob(dir + "/*.mid"):
  print(f)
  try:
    # pr_s is for soprano pianoroll, pr_a is for alto, keymode is for either major 0 or minor 1
    # pr_s, pr_a, keymode = read_midi(f, True, 64)
    pr_s, pr_a, pr_b, keymode = read_midi(f, True, 64)
    # add rests to the pianoroll
    x = add_rest_nodes(pr_s)
    y = add_rest_nodes(pr_a)
    # x = add_rest_nodes(pr_b)
    # y = add_rest_nodes(pr_a)

    # add pianorolls which have been added rest elements to the lists
    x_all.append(x)
    y_all.append(y)
    keymodes.append(keymode)
    files.append(f)
  # throw exception for midi data which can not be used
  except UnsupportedMidiFileException:
    print("skip")
# convert x_all and y_all into NumPy array to make them more useful later
x_all = np.array(x_all)
y_all = np.array(y_all)

Streaming output truncated to the last 5000 lines.
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
rests!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D rests!
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
concatenated!
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
pinoroll!
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0.

KeyboardInterrupt: ignored

In [ ]:
# apply half of the data you stored for training data, and the other half for test data
# the ratio should be 1:1
i_train, i_test = train_test_split(range(len(x_all)),
                                   test_size=int(len(x_all)/2),
                                   shuffle=False)
x_train = x_all[i_train]
x_test = x_all[i_test]
y_train = y_all[i_train]
y_test = y_all[i_test]

In [16]:
# Make and train the model here (LSTM), referred the code 5.1 from the prof book
# code 5.1- implementation of encoder

seq_length = x_train.shape[1] # time length
input_dim = x_train.shape[2] # the number of input dimension
encoded_dim = 16 # the number of vectors you want to compress into
lstm_dim = 1024 # The book's suggested value is 1024. the number of RNN(LSTM) layers' hidden node.

# make an empty model as an encoder part
encoder = tf.keras.Sequential()
# add RNN(LSTM) layers to the model
# return_sequence=Flase means it only returns t he last time vector's value
encoder.add(tf.keras.layers.LSTM(
    lstm_dim, input_shape=(seq_length, input_dim),
    use_bias=True, activation="tanh", return_sequences=False
    ))
#add output layers (encoded_dim will be the number o nodes)
encoder.add(tf.keras.layers.Dense(
    encoded_dim, use_bias=True, activation="linear"
))
# display the model
encoder.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 1024)              4399104   
                                                                 
 dense (Dense)               (None, 16)                16400     
                                                                 
Total params: 4415504 (16.84 MB)
Trainable params: 4415504 (16.84 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
# code 5.2- Implement decoder

#make an empty model
decoder = tf.keras.Sequential()
# Time-series by repeating input layer vectors to be able to add the later RNN(LSTM)
decoder.add(tf.keras.layers.RepeatVector(
    seq_length, input_dim=encoded_dim
  ))
# make LSTM layers and add them to the model
decoder.add(tf.keras.layers.LSTM(
    lstm_dim, use_bias=True, activation="tanh",
    return_sequences=True
    ))

# add output layers to the model. The number of nodes should equal the input's
# return_sequncces is True because decoder is a time-series
# use softmax because the output is one-hot vectors on every time stamps
decoder.add(tf.keras.layers.Dense(
    input_dim, use_bias=True, activation="softmax"
    ))
#display it
decoder.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 repeat_vector (RepeatVecto  (None, 64, 16)            0         
 r)                                                              
                                                                 
 lstm_1 (LSTM)               (None, 64, 1024)          4263936   
                                                                 
 dense_1 (Dense)             (None, 64, 49)            50225     
                                                                 
Total params: 4314161 (16.46 MB)
Trainable params: 4314161 (16.46 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
# code 5.3- concatnate encoder and decoder to make an Auto-encoder
# check

# make a model
model = tf.keras.Model(encoder.inputs, decoder(encoder.outputs))

# compile the model
model.compile(optimizer="adam", loss="categorical_crossentropy",
              metrics="categorical_accuracy")
# dispay
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_input (InputLayer)     [(None, 64, 49)]          0         
                                                                 
 lstm (LSTM)                 (None, 1024)              4399104   
                                                                 
 dense (Dense)               (None, 16)                16400     
                                                                 
 sequential_1 (Sequential)   (None, 64, 49)            4314161   
                                                                 
Total params: 8729665 (33.30 MB)
Trainable params: 8729665 (33.30 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# code 5.4 - the 1st and the 2nd arguments should be the same as input and output should be the same
model.fit(x_train, x_train, batch_size=32, epochs=500)

In [20]:
# code 5.5
model.evaluate(x_test, x_test)

8/8 [==============================] - 1s 23ms/step - loss: 5.0748 - categorical_accuracy: 0.3363


[5.074792861938477, 0.33628541231155396]

In [21]:
# Generate the next note (Using the trained model)
def generate_next_note(model, input_sequence):
  # Use the model to predict the next note
  next_note = model.predict(input_sequence)

  return next_note

In [22]:
# Generate the next note
next_note = generate_next_note(model, x_test)

8/8 [==============================] - 1s 28ms/step


In [ ]:
print(next_note)

In [24]:
def generate_midi_from_notes(notes, output_path):
    # Create a PrettyMIDI object
    midi_data = pretty_midi.PrettyMIDI()

    # Create an Instrument instance for the generated notes
    instrument = pretty_midi.Instrument(0)

    time = 0  # Initialize the time

    # Define a function to convert values in the range [0, 1] to MIDI velocities (0-127)
    def velocity_to_midi(value):
        return int(value * 127)

    # Iterate through the generated notes and create Note instances
    for step in range(len(notes)):
        for note_num, velocity in enumerate(notes[step][0]):
            if velocity > 0:  # Check if the velocity is greater than 0
                # Convert the value to MIDI velocity
                midi_velocity = velocity_to_midi(velocity)

                # Create a Note instance for each active note
                note = pretty_midi.Note(velocity=midi_velocity, pitch=note_num, start=time, end=time+1/32)  # Adjust the duration as needed
                instrument.notes.append(note)

        # Increment the time by one time step
        time += 1/32  # Adjust the time step as needed

    # Add the instrument to the MIDI object
    midi_data.instruments.append(instrument)

    # Write the MIDI data to a file
    midi_data.write(output_path)


In [25]:
generate_midi_from_notes(next_note, output_midi_path)

In [26]:
# failed attempt 1

# # Extract the pitch of the first note from next_note
# next_note_scalar = int(next_note[0][0][0])

# # Create a PrettyMIDI object for the next note
# output_midi = pretty_midi.PrettyMIDI()
# instrument = pretty_midi.Instrument(0)

# # Add the next note to the instrument
# instrument.notes.append(pretty_midi.Note(
#     velocity=64, pitch=next_note_scalar, start=0, end=1
# ))

# # Add the instrument to the MIDI file
# output_midi.instruments.append(instrument)

# # Save the generated note as a new MIDI file
# output_midi.write(output_midi_path)


In [27]:
# failed attempt 2

# def generate_midi_from_notes(notes, output_path):
#     # Create a PrettyMIDI object
#     midi_data = pretty_midi.PrettyMIDI()

#     # Create an Instrument instance for the generated notes
#     instrument = pretty_midi.Instrument(0)

#     time = 0  # Initialize the time

#     # Iterate through the generated notes and create Note instances
#     for step in range(len(notes)):
#         for note_num, velocity in enumerate(notes[step]):
#             if velocity.any() > 0: # to check if any value is greater than 0

#                 # round the velocity to the nearest integer
#                 velocity = np.round(velocity).astype(int)

#                 # ensure the velocity is within the valid MIDI range(0-127)
#                 velocity = np.maximum(0, np.minimum(velocity, 127))

#                 # Create a Note instance for each active note
#                 note = pretty_midi.Note(velocity=velocity, pitch=note_num, start=time, end=time+1/32)  # Adjust the duration as needed
#                 instrument.notes.append(note)

#         # Increment the time by one time step
#         time += 1/32  # Adjust the time step as needed

#     # Add the instrument to the MIDI object
#     midi_data.instruments.append(instrument)

#     # Write the MIDI data to a file
#     print(output_path)
#     midi_data.write(output_path)

# # Generate the MIDI data from "next_note" and save it to a file
# generate_midi_from_notes(next_note, output_midi_path)

In [28]:
# failed attempt 3

# def generate_midi_from_notes(notes, output_path):
#     # Create a PrettyMIDI object
#     midi_data = pretty_midi.PrettyMIDI()

#     # Create an Instrument instance for the generated notes
#     instrument = pretty_midi.Instrument(0)

#     time = 0  # Initialize the time

#     # Iterate through the generated notes and create Note instances
#     for step in range(len(notes)):
#         for note_num, velocity in enumerate(notes[step]):
#             if np.any(velocity > 0):  # Use np.any() to check if any value is greater than zero
#                 # Round the velocity to the nearest integer using np.round
#                 velocity = np.round(velocity).astype(int)

#                 # Ensure the velocity is within the valid MIDI range (0-127)
#                 velocity = np.maximum(0, np.minimum(velocity, 127))

#                 # Create a Note instance for each active note
#                 note = pretty_midi.Note(velocity=velocity, pitch=note_num, start=time, end=time+1/32)  # Adjust the duration as needed
#                 instrument.notes.append(note)

#         # Increment the time by one time step
#         time += 1/32  # Adjust the time step as needed

#     # Add the instrument to the MIDI object
#     midi_data.instruments.append(instrument)

#     # Write the MIDI data to a file
#     midi_data.write(output_path)
