<a href="https://colab.research.google.com/github/TombCrawler/nihonAI/blob/main/TensorTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

referred

In [ ]:
!pip install tensorflow
!pip install --upgrade tensorflow
!pip install keras

In [22]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.datasets import cifar10


initialization of Tensors

In [ ]:
# scaler
x = tf.constant(4, shape=(1,1), dtype=tf.float32)

# Matrix, default 2 * 3 meaning shape=(2,3)
x = tf.constant([[1,2,3], [4,5,6]])

x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) # I for the indentity
x = tf.random.normal((3,3), mean=0, stddev=1) # stddv for standard deviation
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2) # delta is steps.
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


Mathematical Operations


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y)
# z = x + y

z = tf.subtract(x, y)

z = tf.divide(x, y)
z = x/y

z = tf.multiply(x, y)

z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)

z = x ** 5

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[ 0.0623768   1.777854   -0.15115848 -0.57498646]
 [-1.8350759   4.2908087  -0.4893546  -0.20726681]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.0623768   1.777854   -0.15115848 -0.57498646]
 [-1.8350759   4.2908087  -0.4893546  -0.20726681]], shape=(2, 4), dtype=float32)


Indexing

In [ ]:
# # <Vector>
# x = tf.constant([6, 7, 8, 1, 3, 9, 2, 5])
# print(x[:]) # Print all indices
# print(x[1:]) # Starts from index 1 and all
# print(x[1:3]) # Starts from index 1 but exclude index 3
# print(x[::2]) # Skip every other element
# print(x[::-1]) # Reverse order

# # If you want to point specific indices
# indices = tf.constant([0, 3])
# x_ind = tf.gather(x, indices)
# print(x_ind)


# <Matrix>
x = tf.constant([[1,2],
                [3,4],
                [5,6]])
# print(x[0, :]) # Get all the elements in the 1st row. Also you can write this as (x[0])
print(x[0:2, :]) # Specify the indices to get first 2 rows and all the elements in it




Nov 12th 2023 (a day off)
<br>Reshaping  [Official Documentation](https://www.tensorflow.org/api_docs/python/tf/transpose)

In [ ]:
# x = tf.range(9) # A vector which has 9 elements
# print(x)

# x = tf.reshape(x, (3,3)) # reshape the vector to a 3*3 matrix
# print(x)

# x = tf.transpose(x, perm=[1,0]) # Transpose the matrix. perm for permutaion. [1, 0] means just to swap the axis
# print(x)

# For n > 2 dimensional tensors
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
print(x)

x1 = tf.transpose(x) # default
print(x1)
print("-----------------")
x = tf.transpose(x, perm=[0,2,1])
print(x)

Nov 13th 2023 Chapter 3 [link](https://www.youtube.com/watch?v=pAhPiF3yiXI&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=3)

In [ ]:
# Load the mnist data set
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape)
# This is how the printed value look like
#(60000, 28, 28)
# As we send them to NN, we need to flatten them so that we only have one long column with those feature values
# Here is how we do it
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

# -1 means to keep whatever the value is on that dimension, in this case 60,000.
# Then flatten these two dimensions, 28*28
# When we load the data, they are gonna be in numpy arrays, and float 64. So we minimize some of the computation with astype
# And normalize the value by dividing by 255. This is because they are rather than being between 0 and 255, make it between 0 and 1 for faster training
# Do the same thing for x_test

# Play around w/o normlization to see if the result differes
# x_train = x_train.reshape(-1, 28*28).astype("float32")
# x_test = x_test.reshape(-1, 28*28).astype("float32")


Sequential API (very convenient, not very flexible, meaning it only allows you to have one input mapped to one output )
<br><br>[About from_logits=True](https://datascience.stackexchange.com/questions/73093/what-does-from-logits-true-do-in-sparsecategoricalcrossentropy-loss-function)


[Cross Entropy Loss](https://ml-cheatsheet.readthedocs.io/en/latest/loss_functions.html#:~:text=Cross%2Dentropy%20loss%2C%20or%20log,diverges%20from%20the%20actual%20label.)

What "Sparse" means? <br>
It means that the labels, such the y_train labels, are just an integer for that correct label. E.g, if it's a digit of three, the y train o that specific example will just be three. <br>
If you remove the "Sparse", then you need to have **one-hot encodings**.
<br><br>
Optimizers <br>shape and mold your model into its most accurate possible form by futzing with the weights. The loss function is the guide to the terrain(territory), telling the optimizer when it's moving in the right or wrong direction. Optimizers are related to model accuracy, a key component of AI/ML governance.
<br><br>
 "Batch size" <br>refers to the number of training examples utilized in one iteration. In the context of the fit method in TensorFlow/Keras, the batch_size parameter determines the number of samples that will be used in each iteration to update the model's weights.
<br><br>
[Verbose](https://www.educba.com/keras-verbose/) – It will specify the mode of verbosity. <br>
We are defining 0 for silent, one for the progress bar, and two for one line per epoch.

<br>
keras.Input(shape=(28*28)) <br>
Lets you print(model.summary).
<br>
W/o keras.Input, you have to do it after the fit, meaning after you send something to the model to print the model summary

In [ ]:
# Make a model
# Inside sequetial, we are gonna send a list which is layers
# 512 abd such numbers are Nodes.
model = keras.Sequential(
    [
        keras.Input(shape=(28*28)), # Specify the input
        layers.Dense(512, activation='relu'), # first layer
        layers.Dense(256, activation='relu'), # second layer
        layers.Dense(10) # We want to map it to 10 nodes, one node for each digit. Since this is the output layer, we do not need activation function
        # We are gonna use softmax on the output function but it is gonna be done inside the loss function
        ]
)

# print(model.summary())
# import sys
# sys.exit()

# this is to tell Keras how to configure the training part of our network
model.compile(
   loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True), # Specify the loss function we want to use. Check the note above abt the argument.
   # First it sends it into a softmax, and then it's gonna map it to the Crossentropy

   optimizer=keras.optimizers.Adam(learning_rate=0.001), # Specify the optimizers. lr is for Learning Rate
   metrics=["accuracy"] # Keras tracks what is the running accuracy
)

#As you can view it that model.compile specifies the network configurations(designs),
# model.fit, we specify more of the concrete training of THAT network
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2) # verbose=2 prints values after each epoch

#After the training, we want to evaluate
print("\n Here is the evaluation!!!\n")
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

In [16]:
# Good tip for debugging
# You can build a model this way
# This is not the simplest way to write, but you can print the summary each time you add the layer for debugging

model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation='relu'))
# print(model.summary())
model.add(layers.Dense(256, activation='relu', name='tomb_layer')) # you can set the nickname for a layer
model.add(layers.Dense(10))

# this is how you extract specific layer outputs which is useful for debugging also
# first, overwrite the model

# <Call layer with index>
# model = keras.Model(inputs=model.inputs,
#                     outputs=[model.layers[-2].output]) # if you do -1, it is the output layer a.k.a the last one. -2 means you get the one before that

# # <Call layer with a nickname>
# model = keras.Model(inputs=model.inputs,
#                     outputs=[model.get_layer('tomb_layer').output]) # you can call the layer with the nick name instead of index

# feature = model.predict(x_train)
# print(feature.shape) # in this case, 60000 training data and 256 layers which we set as the second layer


# <Call all layers with for loop>
model = keras.Model(inputs=model.inputs,
                    outputs=[layer.output for layer in model.layers])

features = model.predict(x_train)

for feature in features:
  print(feature.shape)





1875/1875 [==============================] - 4s 2ms/step
(60000, 10)
1875/1875 [==============================] - 3s 2ms/step
(60000, 512)
(60000, 256)
(60000, 10)


**Functional API** (a bit more flexible)
<br>
<br>
SUGGESTIONS:<br>
1, Try and see what accuracy you can get by increasing the model, training for longer etc..<br> You should be able to get over 98.1% on the test set!
<br>
<br>
2, Try uing different optimizers than Adam, <br>e.g, Gradient Descent with Momentum
Adagrad, and RMSprop
<br>
<br>
3, Is there any difference if you remove the normalization of the data?


In [ ]:
# Nov 14th 2023

inputs = keras.Input(shape=(784))
x = layers.Dense(512, activation='relu', name='first_layer')(inputs) # Call inputs here
x = layers.Dense(256, activation='relu', name='second_layer')(x) # send in the previous layer in this case, (x)
outputs = layers.Dense(10, activation='softmax')(x)

# make a model
model = keras.Model(inputs=inputs, outputs=outputs)

# print(model.summary())
# import sys
# sys.exit()

# Use the same model aobve except from_logits=False since we used softmax in the output layer
# from_logits=False means default so you can only remove it inside the (), but keep ()
model.compile(
   loss = keras.losses.SparseCategoricalCrossentropy(from_logits=False),

   optimizer=keras.optimizers.Adam(learning_rate=0.001),
   metrics=["accuracy"]
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

print("\n Here is the evaluation!!!\n")
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

**Convolutional NN** [reference](https://youtu.be/WAciKiDP2bo?feature=shared)

<br>
Memo<br>
------------

<br>
layers.Conv2D(32, 3, padding='valid', activation='relu')
<br>-the first argument 32 means how many channels we want this convolutional layer to output. We got 3 channels first then we want it to be 32 channels <br>
-The second argument 3 means we specifying the kernel size. Set a single integer automatically becomes (3,3) or 3*3 kernel size<br>
-padding is that 'valid' is default. Use 'same' keeps the original value of shape, in this case (height 32, width 32)<br>
Using 'valid' changes the value depeding on the kernel size. In this case it becomes 30*30 pixels
<br>


In [27]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0 # 255 is a pixel range, and normalize here make it between 0 and 1
x_test = x_test.astype("float32") / 255.0

# Let's start with Sequential model then make it more advanced later
model = keras.Sequential(
    [
        keras.Input(shape=(32, 32, 3)), # 32 for Height, 32 for Width, 3 for RGB colour channels
        layers.Conv2D(32, 3, padding='valid', activation='relu'), # this line is explained above the note
        layers.MaxPooling2D(pool_size=(2,2)), # 2*2 means half the input size
        layers.Conv2D(64, 3, activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(128, 3, activation='relu'),
        layers.Flatten(), # from here the preparation for the actual output
        layers.Dense(64, activation='relu'), # 64 nodes which is an intermdediate value (can vary)
        layers.Dense(10), # this is the actual output
    ]
)
print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=['accuracy'],


)


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_7 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 15, 15, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_8 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 6, 6, 64)          0         
 g2D)                                                            
                                                                 
 conv2d_9 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 flatten_2 (Flatten)         (None, 2048)             